mod types_positional:

    type Pos:
        line: Int
        col: Int

    enum PosTypeKind:
        PosUnit
        PosInt
        PosString
        PosError(message: String)

    type PosType:
        kind: PosTypeKind

    fn new_pos(line: Int, col: Int) -> !{Heap} Pos:
        ret Pos { line: line, col: col }

    fn pos_type(kind: PosTypeKind) -> !{Heap} PosType:
        ret PosType { kind: kind }
