fn alpha5(n: Int) -> Int:
    if n <= 0:
        ret 0
    else:
        ret beta5(n - 1) + 1

fn beta5(n: Int) -> Int:
    if n <= 0:
        ret 0
    else:
        ret gamma5(n - 1) + 2

fn gamma5(n: Int) -> Int:
    if n <= 0:
        ret 0
    else:
        ret delta5(n - 1) + 3

fn delta5(n: Int) -> Int:
    if n <= 0:
        ret 0
    else:
        ret epsilon5(n - 1) + 4

fn epsilon5(n: Int) -> Int:
    if n <= 0:
        ret 0
    else:
        ret alpha5(n - 1) + 5

fn five_fn_mutual_rec_driver(n: Int) -> Int:
    let a = alpha5(n)
    let b = beta5(n)
    let c = gamma5(n)
    let d = delta5(n)
    let e = epsilon5(n)
    ret a + b + c + d + e
