#!/usr/bin/env bash
# scripts/loc-dashboard.sh — compute Rust-vs-Gradient LoC ratios.
#
# Used by .github/workflows/loc-dashboard.yml to keep
# docs/loc-dashboard.md in sync with the live source tree. Also
# runnable locally to preview the report.
#
# Usage:
#   scripts/loc-dashboard.sh           # write docs/loc-dashboard.md
#   scripts/loc-dashboard.sh --check   # exit 1 if doc is stale (CI)
#   scripts/loc-dashboard.sh --json    # emit machine-readable JSON only
#
# Counts:
#   - Rust kernel:    codebase/compiler/src/**/*.rs
#   - Self-hosted:    compiler/**/*.gr
#   - Stdlib pilot:   codebase/compiler/stdlib/**/*.gr
#   - Trust corpus:   codebase/compiler/tests/bootstrap_trust_corpus/**/*.gr
#
# Honest counting: blank lines, comment-only lines, and code lines are
# all counted as "lines" — same metric for Rust and Gradient so the
# ratio is comparable. Comment-stripping would advantage Gradient
# (Rust has more boilerplate) and obscure the trust artifact.
#
# This script is intentionally pure-bash + standard POSIX tools so it
# runs on every GHA runner without extra dependencies.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

count_lines() {
    # $1 = directory, $2 = extension
    if [ -d "$1" ]; then
        find "$1" -type f -name "*.$2" -not -path '*/target/*' \
            -exec cat {} + 2>/dev/null | wc -l | tr -d ' '
    else
        echo 0
    fi
}

count_files() {
    if [ -d "$1" ]; then
        find "$1" -type f -name "*.$2" -not -path '*/target/*' 2>/dev/null \
            | wc -l | tr -d ' '
    else
        echo 0
    fi
}

RUST_KERNEL_LOC=$(count_lines "codebase/compiler/src" rs)
RUST_KERNEL_FILES=$(count_files "codebase/compiler/src" rs)

GR_SELFHOST_LOC=$(count_lines "compiler" gr)
GR_SELFHOST_FILES=$(count_files "compiler" gr)

GR_STDLIB_LOC=$(count_lines "codebase/compiler/stdlib" gr)
GR_STDLIB_FILES=$(count_files "codebase/compiler/stdlib" gr)

GR_TRUST_LOC=$(count_lines "codebase/compiler/tests/bootstrap_trust_corpus" gr)
GR_TRUST_FILES=$(count_files "codebase/compiler/tests/bootstrap_trust_corpus" gr)

GR_TOTAL_LOC=$(( GR_SELFHOST_LOC + GR_STDLIB_LOC + GR_TRUST_LOC ))
GR_TOTAL_FILES=$(( GR_SELFHOST_FILES + GR_STDLIB_FILES + GR_TRUST_FILES ))

# Self-host share: how much of the compiler is written in Gradient
# vs Rust? Numerator: Gradient self-hosted tree (compiler/*.gr).
# Denominator: Rust kernel + Gradient self-hosted tree.
if [ "$(( RUST_KERNEL_LOC + GR_SELFHOST_LOC ))" -gt 0 ]; then
    SELFHOST_PCT=$(awk "BEGIN { printf \"%.1f\", $GR_SELFHOST_LOC / ($RUST_KERNEL_LOC + $GR_SELFHOST_LOC) * 100 }")
else
    SELFHOST_PCT="0.0"
fi

DATE=$(date -u +"%Y-%m-%d")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# ── Mode dispatch ────────────────────────────────────────────────────

if [ "${1:-}" = "--json" ]; then
    cat <<JSON
{
  "date": "$DATE",
  "commit": "$COMMIT",
  "rust_kernel": { "loc": $RUST_KERNEL_LOC, "files": $RUST_KERNEL_FILES },
  "gradient_selfhost": { "loc": $GR_SELFHOST_LOC, "files": $GR_SELFHOST_FILES },
  "gradient_stdlib": { "loc": $GR_STDLIB_LOC, "files": $GR_STDLIB_FILES },
  "gradient_trust_corpus": { "loc": $GR_TRUST_LOC, "files": $GR_TRUST_FILES },
  "gradient_total": { "loc": $GR_TOTAL_LOC, "files": $GR_TOTAL_FILES },
  "selfhost_share_pct": $SELFHOST_PCT
}
JSON
    exit 0
fi

# Compose the markdown report.
TMP=$(mktemp)
cat > "$TMP" <<MARKDOWN
# LoC Dashboard — Rust kernel vs Gradient self-hosted

> **Auto-generated by [\`scripts/loc-dashboard.sh\`](../scripts/loc-dashboard.sh).** Last refreshed **$DATE** at commit \`$COMMIT\`.
>
> Honest counting: blank lines + comments + code lines, same metric for Rust and Gradient. Excludes \`target/\`. See script source for exact paths.

## Snapshot

| Component | Files | Lines | Notes |
|---|---:|---:|---|
| Rust kernel — \`codebase/compiler/src/\` | $RUST_KERNEL_FILES | $RUST_KERNEL_LOC | Reference compiler (lex/parse/check/lower/codegen + bootstrap kernels) |
| Gradient self-hosted compiler — \`compiler/\` | $GR_SELFHOST_FILES | $GR_SELFHOST_LOC | Bootstrap-stage delegating modules + LSP handler set |
| Gradient stdlib pilot — \`codebase/compiler/stdlib/\` | $GR_STDLIB_FILES | $GR_STDLIB_LOC | \`@verified\` SMT-discharged modules (E4 launch tier) |
| Gradient trust corpus — \`codebase/compiler/tests/bootstrap_trust_corpus/\` | $GR_TRUST_FILES | $GR_TRUST_LOC | Bootstrap-subset compile-through fixtures + sad-path fixtures |
| **Gradient total** | **$GR_TOTAL_FILES** | **$GR_TOTAL_LOC** | All \`.gr\` files in repo |

## Self-hosting share (compiler-only)

\`\`\`
self-host share = compiler/*.gr  /  (codebase/compiler/src/*.rs + compiler/*.gr)
                = $GR_SELFHOST_LOC / ($RUST_KERNEL_LOC + $GR_SELFHOST_LOC)
                = ${SELFHOST_PCT}%
\`\`\`

This is the headline number for Epic [#116](https://github.com/Ontic-Systems/Gradient/issues/116) (\"95%+ in Gradient with Minimal Rust Kernel\"). It excludes the stdlib pilot and trust corpus — those are *artifacts produced by* the compiler, not part of it.

## What this measures, what it does not

This dashboard is a **rough trust artifact**, not a verified bootstrap claim. It tells you:

- ✅ The relative size of the Rust kernel vs the self-hosted \`.gr\` tree.
- ✅ How much Gradient code lives in the repo as stdlib + trust corpus (which the compiler must accept on every CI green).

It does **not** tell you:

- ❌ Whether the self-hosted compiler actually executes (it does not yet — see [docs/SELF_HOSTING.md](SELF_HOSTING.md)).
- ❌ Which kernel surfaces are \`SelfHostedDefault\` vs \`Hybrid\` (see \`codebase/compiler/src/kernel_boundary.rs\`).
- ❌ Whether the Rust kernel is \"minimal\" in the post-#116 sense.

For the honest split between Rust-hosted alpha, self-hosting bootstrap alpha, and true self-hosted compiler alpha, see [\`docs/SELF_HOSTING.md\`](SELF_HOSTING.md) and the \"alpha-readiness assessment\" section of the internal handoff.

## Cross-references

- Epic [#116](https://github.com/Ontic-Systems/Gradient/issues/116) — Full Self-Hosting: 95%+ in Gradient with Minimal Rust Kernel.
- Sub-issue [#381](https://github.com/Ontic-Systems/Gradient/issues/381) — public Rust-vs-Gradient LoC dashboard (this artifact).
- Workflow: [\`.github/workflows/loc-dashboard.yml\`](../.github/workflows/loc-dashboard.yml).
- Generator script: [\`scripts/loc-dashboard.sh\`](../scripts/loc-dashboard.sh).

## How to refresh locally

\`\`\`bash
scripts/loc-dashboard.sh             # rewrites docs/loc-dashboard.md
scripts/loc-dashboard.sh --json      # emit raw JSON
scripts/loc-dashboard.sh --check     # exit non-zero if doc is stale
\`\`\`

The CI lane runs \`--check\` on every PR; nightly main runs without
\`--check\` and commits any drift back to main.
MARKDOWN

if [ "${1:-}" = "--check" ]; then
    if [ -f docs/loc-dashboard.md ]; then
        # Compare ignoring the date + commit lines (which always differ).
        if diff -q \
            <(grep -v '^> \*\*Auto-generated' docs/loc-dashboard.md) \
            <(grep -v '^> \*\*Auto-generated' "$TMP") \
            > /dev/null; then
            rm -f "$TMP"
            echo "loc-dashboard.md is up-to-date (ignoring date/commit header)."
            exit 0
        fi
        echo "ERROR: docs/loc-dashboard.md is stale. Run scripts/loc-dashboard.sh and commit." >&2
        diff -u docs/loc-dashboard.md "$TMP" >&2 || true
        rm -f "$TMP"
        exit 1
    else
        echo "ERROR: docs/loc-dashboard.md missing. Run scripts/loc-dashboard.sh and commit." >&2
        rm -f "$TMP"
        exit 1
    fi
fi

mv "$TMP" docs/loc-dashboard.md
echo "Wrote docs/loc-dashboard.md (commit=$COMMIT)."
